# Generated by Django 3.0.8 on 2020-07-25 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_auto_20200723_0900'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stuid', models.CharField(max_length=10)),
                ('stuName', models.CharField(max_length=50)),
                ('branch', models.CharField(choices=[('CSE', 'cse'), ('ECE', 'ece'), ('MECH', 'mech'), ('IT', 'it')], max_length=50)),
                ('age', models.IntegerField()),
            ],
        ),
    ]
