# Generated by Django 3.0.8 on 2020-07-27 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Firstapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='email',
            name='password',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
